var modules =
[
    [ "Analog-to-Digital Converter", "group__SAM3XA__ADC.html", null ],
    [ "Controller Area Network", "group__SAM3XA__CAN.html", null ],
    [ "Chip Identifier", "group__SAM3XA__CHIPID.html", null ],
    [ "Digital-to-Analog Converter Controller", "group__SAM3XA__DACC.html", null ],
    [ "DMA Controller", "group__SAM3XA__DMAC.html", null ],
    [ "Embedded Flash Controller", "group__SAM3XA__EFC.html", null ],
    [ "Ethernet MAC 10/100", "group__SAM3XA__EMAC.html", null ],
    [ "General Purpose Backup Registers", "group__SAM3XA__GPBR.html", null ],
    [ "High Speed MultiMedia Card Interface", "group__SAM3XA__HSMCI.html", null ],
    [ "AHB Bus Matrix", "group__SAM3XA__MATRIX.html", null ],
    [ "Peripheral DMA Controller", "group__SAM3XA__PDC.html", null ],
    [ "Parallel Input/Output Controller", "group__SAM3XA__PIO.html", null ],
    [ "Power Management Controller", "group__SAM3XA__PMC.html", null ],
    [ "Pulse Width Modulation Controller", "group__SAM3XA__PWM.html", null ],
    [ "Reset Controller", "group__SAM3XA__RSTC.html", null ],
    [ "Real-time Clock", "group__SAM3XA__RTC.html", null ],
    [ "Real-time Timer", "group__SAM3XA__RTT.html", null ],
    [ "SDRAM Controller", "group__SAM3XA__SDRAMC.html", null ],
    [ "Static Memory Controller", "group__SAM3XA__SMC.html", null ],
    [ "Serial Peripheral Interface", "group__SAM3XA__SPI.html", null ],
    [ "Synchronous Serial Controller", "group__SAM3XA__SSC.html", null ],
    [ "Supply Controller", "group__SAM3XA__SUPC.html", null ],
    [ "Timer Counter", "group__SAM3XA__TC.html", null ],
    [ "True Random Number Generator", "group__SAM3XA__TRNG.html", null ],
    [ "Two-wire Interface", "group__SAM3XA__TWI.html", null ],
    [ "Universal Asynchronous Receiver Transmitter", "group__SAM3XA__UART.html", null ],
    [ "USB On-The-Go Interface", "group__SAM3XA__UOTGHS.html", null ],
    [ "Universal Synchronous Asynchronous Receiver Transmitter", "group__SAM3XA__USART.html", null ],
    [ "Watchdog Timer", "group__SAM3XA__WDT.html", null ],
    [ "SAM3A4C definitions", "group__SAM3A4C__definitions.html", null ],
    [ "CMSIS Definitions", "group__SAM3A4C__cmsis.html", null ],
    [ "Peripheral Software API", "group__SAM3A4C__api.html", null ],
    [ "Registers Access Definitions", "group__SAM3A4C__reg.html", null ],
    [ "Peripheral Ids Definitions", "group__SAM3A4C__id.html", null ],
    [ "Peripheral Base Address Definitions", "group__SAM3A4C__base.html", null ],
    [ "Peripheral Pio Definitions", "group__SAM3A4C__pio.html", null ],
    [ "SAM3A8C definitions", "group__SAM3A8C__definitions.html", null ],
    [ "CMSIS Definitions", "group__SAM3A8C__cmsis.html", null ],
    [ "Peripheral Software API", "group__SAM3A8C__api.html", null ],
    [ "Registers Access Definitions", "group__SAM3A8C__reg.html", null ],
    [ "Peripheral Ids Definitions", "group__SAM3A8C__id.html", null ],
    [ "Peripheral Base Address Definitions", "group__SAM3A8C__base.html", null ],
    [ "Peripheral Pio Definitions", "group__SAM3A8C__pio.html", null ],
    [ "SAM3X4C definitions", "group__SAM3X4C__definitions.html", null ],
    [ "CMSIS Definitions", "group__SAM3X4C__cmsis.html", null ],
    [ "Peripheral Software API", "group__SAM3X4C__api.html", null ],
    [ "Registers Access Definitions", "group__SAM3X4C__reg.html", null ],
    [ "Peripheral Ids Definitions", "group__SAM3X4C__id.html", null ],
    [ "Peripheral Base Address Definitions", "group__SAM3X4C__base.html", null ],
    [ "Peripheral Pio Definitions", "group__SAM3X4C__pio.html", null ],
    [ "SAM3X4E definitions", "group__SAM3X4E__definitions.html", null ],
    [ "CMSIS Definitions", "group__SAM3X4E__cmsis.html", null ],
    [ "Peripheral Software API", "group__SAM3X4E__api.html", null ],
    [ "Registers Access Definitions", "group__SAM3X4E__reg.html", null ],
    [ "Peripheral Ids Definitions", "group__SAM3X4E__id.html", null ],
    [ "Peripheral Base Address Definitions", "group__SAM3X4E__base.html", null ],
    [ "Peripheral Pio Definitions", "group__SAM3X4E__pio.html", null ],
    [ "SAM3X8C definitions", "group__SAM3X8C__definitions.html", null ],
    [ "CMSIS Definitions", "group__SAM3X8C__cmsis.html", null ],
    [ "Peripheral Software API", "group__SAM3X8C__api.html", null ],
    [ "Registers Access Definitions", "group__SAM3X8C__reg.html", null ],
    [ "Peripheral Ids Definitions", "group__SAM3X8C__id.html", null ],
    [ "Peripheral Base Address Definitions", "group__SAM3X8C__base.html", null ],
    [ "Peripheral Pio Definitions", "group__SAM3X8C__pio.html", null ],
    [ "SAM3X8E definitions", "group__SAM3X8E__definitions.html", null ],
    [ "CMSIS Definitions", "group__SAM3X8E__cmsis.html", null ],
    [ "Peripheral Software API", "group__SAM3X8E__api.html", null ],
    [ "Peripheral Ids Definitions", "group__SAM3X8E__id.html", null ],
    [ "Peripheral Base Address Definitions", "group__SAM3X8E__base.html", null ],
    [ "Peripheral Pio Definitions", "group__SAM3X8E__pio.html", null ],
    [ "SAM3X8H definitions", "group__SAM3X8H__definitions.html", null ],
    [ "CMSIS Definitions", "group__SAM3X8H__cmsis.html", null ],
    [ "Peripheral Software API", "group__SAM3X8H__api.html", null ],
    [ "Registers Access Definitions", "group__SAM3X8H__reg.html", null ],
    [ "Peripheral Ids Definitions", "group__SAM3X8H__id.html", null ],
    [ "Peripheral Base Address Definitions", "group__SAM3X8H__base.html", null ],
    [ "Peripheral Pio Definitions", "group__SAM3X8H__pio.html", null ]
];