var searchData=
[
  ['parallel_20input_2foutput_20controller_0',['Parallel Input/Output Controller',['../group__SAM3XA__PIO.html',1,'']]],
  ['peripheral_20base_20address_20definitions_1',['Peripheral Base Address Definitions',['../group__SAM3A4C__base.html',1,'(Global Namespace)'],['../group__SAM3A8C__base.html',1,'(Global Namespace)'],['../group__SAM3X4C__base.html',1,'(Global Namespace)'],['../group__SAM3X4E__base.html',1,'(Global Namespace)'],['../group__SAM3X8C__base.html',1,'(Global Namespace)'],['../group__SAM3X8E__base.html',1,'(Global Namespace)'],['../group__SAM3X8H__base.html',1,'(Global Namespace)']]],
  ['peripheral_20dma_20controller_2',['Peripheral DMA Controller',['../group__SAM3XA__PDC.html',1,'']]],
  ['peripheral_20ids_20definitions_3',['Peripheral Ids Definitions',['../group__SAM3A4C__id.html',1,'(Global Namespace)'],['../group__SAM3A8C__id.html',1,'(Global Namespace)'],['../group__SAM3X4C__id.html',1,'(Global Namespace)'],['../group__SAM3X4E__id.html',1,'(Global Namespace)'],['../group__SAM3X8C__id.html',1,'(Global Namespace)'],['../group__SAM3X8E__id.html',1,'(Global Namespace)'],['../group__SAM3X8H__id.html',1,'(Global Namespace)']]],
  ['peripheral_20pio_20definitions_4',['Peripheral Pio Definitions',['../group__SAM3A4C__pio.html',1,'(Global Namespace)'],['../group__SAM3A8C__pio.html',1,'(Global Namespace)'],['../group__SAM3X4C__pio.html',1,'(Global Namespace)'],['../group__SAM3X4E__pio.html',1,'(Global Namespace)'],['../group__SAM3X8C__pio.html',1,'(Global Namespace)'],['../group__SAM3X8E__pio.html',1,'(Global Namespace)'],['../group__SAM3X8H__pio.html',1,'(Global Namespace)']]],
  ['peripheral_20software_20api_5',['Peripheral Software API',['../group__SAM3A4C__api.html',1,'(Global Namespace)'],['../group__SAM3A8C__api.html',1,'(Global Namespace)'],['../group__SAM3X4C__api.html',1,'(Global Namespace)'],['../group__SAM3X4E__api.html',1,'(Global Namespace)'],['../group__SAM3X8C__api.html',1,'(Global Namespace)'],['../group__SAM3X8E__api.html',1,'(Global Namespace)'],['../group__SAM3X8H__api.html',1,'(Global Namespace)']]],
  ['power_20management_20controller_6',['Power Management Controller',['../group__SAM3XA__PMC.html',1,'']]],
  ['pulse_20width_20modulation_20controller_7',['Pulse Width Modulation Controller',['../group__SAM3XA__PWM.html',1,'']]]
];
